version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - "dependabot"
    reviewers:
      - "ega4432"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - "dependabot"
    reviewers:
      - "ega4432"
