name: 'notion-to-markdown-action'
description: 'Download notion pages to markdown files.'
author: 'ega4432'
inputs:
  notion_api_key:
    required: true
    description: 'API key of Notion integrations.'
  notion_database_id:
    required: true
    description: 'Database ID of target Notion page.'
  output_path:
    required: false
    description: 'Directory path to output files.'
    default: 'output'
  filename_property:
    required: false
    description: 'A property to be used as the markdown file name.'
    default: 'title'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'download-cloud'
  color: 'blue'
